# Generated by Django 3.2.18 on 2023-05-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='star_ranking',
        ),
    ]
