# Generated by Django 3.2.18 on 2023-05-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='review_product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.product'),
        ),
    ]
