# Generated by Django 3.2.18 on 2023-05-07 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_remove_article_star_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='basket',
            field=models.ManyToManyField(null=True, related_name='basket_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
